# Generated by Django 5.2.6 on 2025-10-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_id',
            new_name='user',
        ),
    ]
