# Generated by Django 5.2.6 on 2025-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_category_id_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitexpense',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
