# Generated by Django 5.2.6 on 2025-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_splitexpense_group_name_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
