# Generated by Django 5.2.6 on 2025-10-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ex',
        ),
    ]
